import React, {useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import * as XLSX from 'xlsx';
import {seedData} from './seedData';
import './styles.css';

const KEY='the-boss-mpg-v1';
const money=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'});
const num=(n,d=2)=>Number.isFinite(n)?n.toFixed(d):'—';
const uid=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`;
function initial(){try{const x=JSON.parse(localStorage.getItem(KEY)); if(x?.fuel&&x?.def)return x;}catch{} return seedData;}
function calc(rows){return [...rows].sort((a,b)=>a.date.localeCompare(b.date)).map((r,i,all)=>{const prev=all[i-1];const distance=Number(r.distance)||((prev&&r.odometer>prev.odometer)?r.odometer-prev.odometer:0);return {...r,distance,efficiency:r.gallons?distance/r.gallons:0,unitCost:r.gallons?r.cost/r.gallons:0,costMile:distance?r.cost/distance:0};});}
function Summary({rows,type}){const totalMiles=rows.reduce((s,r)=>s+r.distance,0), gallons=rows.reduce((s,r)=>s+r.gallons,0), cost=rows.reduce((s,r)=>s+r.cost,0);return <div className="cards"><article><span>Total miles</span><b>{num(totalMiles,0)}</b></article><article><span>{type==='fuel'?'Average MPG':'Miles / DEF gal'}</span><b>{num(gallons?totalMiles/gallons:0)}</b></article><article><span>Total gallons</span><b>{num(gallons,2)}</b></article><article><span>Total cost</span><b>{money.format(cost)}</b></article></div>}
function App(){
 const [data,setData]=useState(initial); const [tab,setTab]=useState('fuel'); const [msg,setMsg]=useState('');
 const [form,setForm]=useState({date:new Date().toISOString().slice(0,10),odometer:'',gallons:'',cost:''});
 const rows=useMemo(()=>calc(data[tab]),[data,tab]);
 const save=n=>{setData(n);localStorage.setItem(KEY,JSON.stringify(n));};
 const add=e=>{e.preventDefault();const odometer=+form.odometer,gallons=+form.gallons,cost=+form.cost;if(!form.date||odometer<=0||gallons<=0||cost<0)return setMsg('Enter a valid date, odometer, gallons, and cost.');const prev=rows.at(-1);const distance=prev&&odometer>prev.odometer?odometer-prev.odometer:0;save({...data,[tab]:[...data[tab],{id:uid(),type:tab,date:form.date,odometer,gallons,cost,distance}]});setForm(f=>({...f,odometer:'',gallons:'',cost:''}));setMsg(distance?'Entry saved.':'Entry saved. Add a later odometer reading to calculate distance.');};
 const remove=id=>save({...data,[tab]:data[tab].filter(x=>x.id!==id)});
 const exportFile=()=>{const wb=XLSX.utils.book_new();for(const t of ['fuel','def']){const out=calc(data[t]).map(r=>({Type:t==='fuel'?'Diesel':'DEF',Date:r.date,Odometer:r.odometer,'Miles since prior fill':r.distance,Gallons:r.gallons,Cost:r.cost,'Cost/Gallon':r.unitCost,'Miles/Gallon':r.efficiency,'Cost/Mile':r.costMile}));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(out),t==='fuel'?'Diesel':'DEF');}XLSX.writeFile(wb,'The-Boss-MPG-Backup.xlsx');};
 const importFile=async e=>{const file=e.target.files[0];if(!file)return;try{const wb=XLSX.read(await file.arrayBuffer(),{cellDates:true});const imported={fuel:[],def:[]};const parse=(sheet,type)=>{const a=XLSX.utils.sheet_to_json(sheet,{defval:''});a.forEach((r,i)=>{const date=r.Date||r.DATE;const odo=+(r.Odometer||r['EndODO']||r['END ODO']);const gallons=+(r.Gallons||r['TOTAL GALLONS']);const cost=+(r.Cost||r['TOTAL FUEL COST']||r['TOTAL DEF COST']);const distance=+(r['Miles since prior fill']||r['TRIP METER']||r['Trip miles']);if(date&&gallons){const ds=date instanceof Date?date.toISOString().slice(0,10):String(date);imported[type].push({id:`import-${type}-${i}-${uid()}`,type,date:ds,odometer:odo||0,gallons,cost,distance});}})};wb.SheetNames.forEach(n=>parse(wb.Sheets[n],n.toLowerCase().includes('def')?'def':'fuel')); if(!imported.fuel.length&&!imported.def.length)throw Error();save({fuel:imported.fuel.length?imported.fuel:data.fuel,def:imported.def.length?imported.def:data.def});setMsg('Spreadsheet imported.');}catch{setMsg('Could not read that layout. Use the exported backup format or the original tracker workbook.');}e.target.value='';};
 return <main><header><div><p className="eyebrow">THE BOSS</p><h1>MPG Tracker</h1><p>Diesel and DEF fill-up history, all in one place.</p></div><div className="actions"><label className="button secondary">Import Excel<input type="file" accept=".xlsx,.xls" onChange={importFile}/></label><button className="button secondary" onClick={exportFile}>Export backup</button></div></header>
 <nav><button className={tab==='fuel'?'active':''} onClick={()=>setTab('fuel')}>Diesel</button><button className={tab==='def'?'active':''} onClick={()=>setTab('def')}>DEF</button></nav>
 <Summary rows={rows} type={tab}/>
 <section className="panel"><h2>Add {tab==='fuel'?'diesel':'DEF'} fill-up</h2><form onSubmit={add}><label>Date<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label><label>Truck odometer<input inputMode="decimal" placeholder="24,750" value={form.odometer} onChange={e=>setForm({...form,odometer:e.target.value.replace(/,/g,'')})}/></label><label>Gallons<input inputMode="decimal" placeholder="18.5" value={form.gallons} onChange={e=>setForm({...form,gallons:e.target.value})}/></label><label>Fuel cost<input inputMode="decimal" placeholder="105.00" value={form.cost} onChange={e=>setForm({...form,cost:e.target.value})}/></label><button className="button" type="submit">Save fill-up</button></form>{msg&&<p className="message">{msg}</p>}</section>
 <section className="panel tablePanel"><div className="sectionHead"><h2>History</h2><span>{rows.length} entries</span></div><div className="tableWrap"><table><thead><tr><th>Date</th><th>Odometer</th><th>Miles</th><th>Gallons</th><th>Cost</th><th>$/gal</th><th>{tab==='fuel'?'MPG':'Miles/DEF gal'}</th><th></th></tr></thead><tbody>{[...rows].reverse().map(r=><tr key={r.id}><td>{r.date}</td><td>{num(r.odometer,0)}</td><td>{num(r.distance,0)}</td><td>{num(r.gallons)}</td><td>{money.format(r.cost)}</td><td>{money.format(r.unitCost)}</td><td className="strong">{num(r.efficiency)}</td><td><button className="delete" onClick={()=>remove(r.id)} aria-label="Delete entry">×</button></td></tr>)}</tbody></table></div></section>
 <footer>Data is saved in this browser. Export a backup regularly.</footer></main>}
createRoot(document.getElementById('root')).render(<App/>);
